### PR TITLE
fix iOS 9

### PR DESCRIPTION
**Pull request by verygenericname**
fix dyld error on iOS 9

### CODE REVIEW

**Comment by verygenericname** [comment]
just tested with a iPod 7 running 14.4, with a 5s running 9.2.1, before it would just error with a dyld load command error

**Comment by verygenericname** [comment]
still works on latest ios too

**Comment by dora2-iOS** [comment]
If you add it, please make sure to set it to 9.0.

**Comment by verygenericname** [comment]
done

**Comment by dora2-iOS** [comment]
By the way, what kind of error will occur if you build in which environment?

**Comment by verygenericname** [comment]
i forgot what error exactly, but goes by the line of Dyld info load command not found, but setting the mios version fixed it, i compiled on a hackintosh running monterey

**Pull request merged**
